## Adding Layers 

Firstly, we will copy paste the inital batch of inputs and weigths and add the new weights and biases to create a new layer

In [2]:
import numpy as np 

In [1]:
inputs = [[1,2,3,2.5],
          [2.,5.,-1.,2.],
          [-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
biases =  [2,3,0.5] 

weights2 = [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]
biases2 = [-1,2,-0.5] 

In [3]:
layer1_outputs = np.dot(inputs,np.array(weights).T) + biases 

In [4]:
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

In [5]:
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


**At this point, our neural network should look like:**
![alt text](neurons_with_2_hidden_layers.png "Title")

In [1]:
from nnfs.datasets import spiral_data

In [2]:
import numpy as np 
import nnfs 

In [3]:
nnfs.init()

nnfs.init() does three things: it sets the random seed to 0(by the default),creates a float32 dtype default, and overrides the original dot produt from NumPy. All of these are meant to ensure repeatable results for following along. 

In [5]:
# Dense Layer 
class Layer_Dense: 
    #Layer initialization 
    def __init__(self,n_inputs, n_neurons):
        # Initialize weights and biases 
        self.weights = 0.01*np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))

    #Forward pass 
    def forward(self,inputs):
         # Calculate out values from inputs, weights and biases 
        self.output = np.dot(inputs,self.weights)+self.biases

# Create a dataset 
X,y = spiral_data(samples = 100,classes =3)
#Create a Dense Layer with with 2 input features and 3 output values 
dense1 = Layer_Dense(2,3)
dense1.forward(X)
# Let's see output of the first few samples: 
print(dense1.output[:5])



[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.61496298e-05 -5.70940247e-05 -1.16960771e-04]
 [-7.69893813e-05 -4.75328154e-04 -2.12466970e-04]
 [-1.19454686e-04 -6.26299181e-04 -3.77396704e-04]
 [-1.59333722e-04 -8.86327529e-04 -4.81519091e-04]]
