## Adding Layers 

Firstly, we will copy paste the inital batch of inputs and weigths and add the new weights and biases to create a new layer

In [2]:
import numpy as np 

In [1]:
inputs = [[1,2,3,2.5],
          [2.,5.,-1.,2.],
          [-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
biases =  [2,3,0.5] 

weights2 = [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]
biases2 = [-1,2,-0.5] 

In [3]:
layer1_outputs = np.dot(inputs,np.array(weights).T) + biases 

In [4]:
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

In [5]:
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


**At this point, our neural network should look like:**
![alt text](neurons_with_2_hidden_layers.png "Title")

In [17]:
from nnfs.datasets import spiral_data

In [18]:
import numpy as np 
import nnfs 

In [19]:
nnfs.init()

nnfs.init() does three things: it sets the random seed to 0(by the default),creates a float32 dtype default, and overrides the original dot produt from NumPy. All of these are meant to ensure repeatable results for following along. 

In [20]:
# Dense Layer 
class Layer_Dense: 
    #Layer initialization 
    def __init__(self,n_inputs, n_neurons):
        # Initialize weights and biases 
        self.weights = 0.01*np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))

    #Forward pass 
    def forward(self,inputs):
         # Calculate out values from inputs, weights and biases 
        self.output = np.dot(inputs,self.weights)+self.biases

# Create a dataset 
X,y = spiral_data(samples = 100,classes =3)
#Create a Dense Layer with with 2 input features and 3 output values 
dense1 = Layer_Dense(2,3)
dense1.forward(X)
# Let's see output of the first few samples: 
print(dense1.output[:5])



[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]


### ReLU Activation function 

In [21]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100] 

output = [] 
for i in inputs: 
    if i > 0: 
        output.append(i)
    else: 
        output.append(0)
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [22]:
import numpy as np 
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100] 
output = np.maximum(0,inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [23]:
class Activation_ReLU: 
    #Forward pass 
    def forward(self,inputs):
        # Calculate output values from input 
        self.output = np.maximum(0,inputs)

In [24]:
X, y = spiral_data(samples=100,classes=3)

#Create Dense layer with 2 input features and 3 output values 
dense1 = Layer_Dense(2,3)

# Create ReLU activation ( to be used with Dense Layer): 
activation1 = Activation_ReLU()

# Make a forward pass of our training data through this layer 
dense1.forward(X)

# Forward pass through activation func. 
#Takes in output from previous layer
activation1.forward(dense1.output)

#Let's see output of the first few samples 
print(activation1.output[:5])


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Softmax Activation Function 

In [3]:
layer_outputs = [4.8,1,21,2,385]
e = 2.71828182846 #math.e can also be used 

In [5]:
exp_values = [] 
for output in layer_outputs: 
    exp_values.append(e**output) # ** - power operator in python
print("exponentiated values:") 
print(exp_values)

exponentiated values:
[121.51041751893969, 2.71828182846, 1318815734.4929411, 7.38905609893584, 1.5972596947447657e+167]


In [7]:
# Now normalize values 
norm_base = sum(exp_values) 
norm_values = [] 
for value in exp_values: 
    norm_values.append(value/norm_base)
print('Normalized exponentiated values:')
print(norm_values)

print('Sum of normalized values:',sum(norm_values)) 


Normalized exponentiated values:
[7.607430270652166e-166, 1.7018408699622063e-167, 8.256739582373807e-159, 4.626083111748822e-167, 1.0]
Sum of normalized values: 1.0


#### Things can be done in numpy in following way

In [1]:
import numpy as np 

In [2]:
layer_outputs = [4.8, 1.21,2.385] 
# For each value in a vector, calculate the exponential value 
exp_values = np.exp(layer_outputs) 
print('exponentiated values:') 
print( exp_values) 

exponentiated values:
[121.51041752   3.35348465  10.85906266]


In [3]:
#Now normalize values 
norm_values = exp_values / np.sum(exp_values) 
print('normalized exponential values:') 
print(norm_values) 
print('sum of normalized values:',np.sum(norm_values))


normalized exponential values:
[0.89528266 0.02470831 0.08000903]
sum of normalized values: 0.9999999999999999


# Full code + Additional code upto this point


In [2]:
import numpy as np 
import nnfs 
from nnfs.datasets import spiral_data 

In [3]:
nnfs.init()

In [19]:
#Dense Layer 
class Layer_Dense:
    #Layer initilization 
    def __init__(self, n_inputs, n_neurons):
        #Initialize weights and biases 
        self.weights = 0.01*np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    # Forward pass
    def forward(self,inputs):
        # Calculate output values from inputs, weight and biases 
        self.output = np.dot(inputs,self.weights) + self.biases 

# Activation ReLU 
class Activation_ReLU: 
     #Forward pass 
     def forward(self,inputs): 
         # Calculate ouput values from inputs 
        self.output = np.maximum(0,inputs) 
class Activation_softmax: 
        # Forward pass 
        def forward(self, inputs):

            #Get unnormalized probabilities 
            exp_values = np.exp(inputs - np.max(inputs, axis =1,
                                                keepdims = True))

            # Normalize them for each sample 
            probabilities = exp_values / np.sum(exp_values , axis=1,
                                               keepdims=True)
            self.output = probabilities
                
    

In [20]:
# Create dataset 
X,y = spiral_data(samples = 100, classes = 3) 

# Create Dense layer with 2 input features and 3 output values 
dense1 = Layer_Dense(2,3)
# Create ReLU activation (to be used with Dense layer ) 
activation1 = Activation_ReLU() 

#Create second dense layer with 3 input features ( as we take output
# of previous layer here) and 3 output values
dense2 = Layer_Dense(3,3)

#Create Softmax activation ( to be used with Dense Layer) 
activation2 = Activation_softmax()

# Make a  forward pass of our training data through the first layer 
dense1.forward(X)  

# make a forward pass through activation function 
# it takes the output of first dense layer here 
activation1.forward(dense1.output)

# it takes output of activation function of first layer as inputs

dense2.forward(activation1.output)

# Make a forward pass through 2nd activation function 
# It takes the output of second dense layer here 
activation2.forward(dense2.output) 

In [21]:
# Let's see output of the first few samples: 
print(activation2.output)

[[0.33333334 0.33333334 0.33333334]
 [0.33333355 0.33333337 0.33333308]
 [0.3333336  0.33333415 0.33333224]
 [0.33333397 0.33333427 0.33333182]
 [0.33333388 0.33333504 0.33333114]
 [0.33333412 0.33333528 0.33333057]
 [0.33333308 0.33333614 0.33333078]
 [0.33333337 0.33333647 0.33333018]
 [0.3333332  0.333337   0.3333298 ]
 [0.33333415 0.33333734 0.3333285 ]
 [0.33333212 0.33333832 0.3333296 ]
 [0.33332893 0.33333874 0.33333233]
 [0.33333388 0.33333877 0.33332735]
 [0.3333308  0.33334    0.33332914]
 [0.33333462 0.33333957 0.3333258 ]
 [0.33332664 0.33334157 0.33333176]
 [0.33333012 0.33334154 0.33332837]
 [0.33332607 0.3333423  0.3333316 ]
 [0.3333336  0.33334124 0.33332512]
 [0.33332497 0.33334368 0.3333314 ]
 [0.33332607 0.33334303 0.3333309 ]
 [0.33332366 0.3333453  0.33333108]
 [0.33332333 0.33334565 0.33333102]
 [0.33332315 0.3333459  0.33333096]
 [0.3333253  0.33334327 0.33333144]
 [0.33332542 0.33334595 0.3333286 ]
 [0.33332172 0.33334768 0.33333063]
 [0.33332354 0.33334538 0.33

300